#! /bin/sh
export PATH="${PATH}:$HOME/.local/bin:$HOME/.config/bspwm/bin:/home/linuxbrew/.linuxbrew/bin"
export BSPWM_PATH=$HOME/.config/bspwm

pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor DP-2 -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI-0 -d 10 11 12 13 14 15 16 17 18 19


bspc config border_width         3
bspc config focused_border_color "#229922"
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a gnome-calculator state=floating
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

