#!/usr/bin/env bash

SHELF_SPACE=5 # space number to use as the floating window holder 

declare -A configuredWindowFilters

configuredWindowFilters[teams]='[.[] | select(.layer == "normal" and (.app | startswith("Microsoft Teams")) and ."is-floating" == true)] | sort_by(.id) | .[-1]'
configuredWindowFilters[slack]='[.[] | select(.app == "Slack")][0]'
configuredWindowFilters[obsidian]='[.[] | select(.app == "Obsidian" and ."is-floating" == true)][0]'
configuredWindowFilters[wezterm]='[.[] | select(.app == "WezTerm" and ."is-floating" == true)][0]'
configuredWindowFilters[ghostty]='[.[] | select(.app == "Ghostty" and ."is-floating" == true and .layer == "normal")][0]'
configuredWindowFilters[telegram]='[.[] | select(.app == "Telegram" and ."is-floating" == true)][0]'

configuredWindowFilters[postman]='[.[] | select(.app == "Postman" and ."is-floating" == true)][0]'
configuredWindowFilters[orion]='[.[] | select(.app == "Orion" and ."is-floating" == true)][0]'
configuredWindowFilters[vivaldi]='[.[] | select(.app == "Vivaldi" and ."is-floating" == true)][0]'
configuredWindowFilters[zed]='[.[] | select(.layer == "normal" and .app == "Zed" and ."is-floating" == true)] | sort_by(.id) | .[-1]'


function getCurrentSpace() {
    yabai -m query --windows --window | gojq '(.space, .id)'
}

function getTargetWindow() {
    yabai -m query --windows | gojq "${configuredWindowFilters[$1]}"
}

function refocusManagedWindow() {
    firstManagedWindow=$(yabai -m query --windows --space | gojq -r '[.[] | select(."is-floating" == false and .layer == "normal")][0] | .id') 
    if [[ ! -z $firstManagedWindow ]]; then
        yabai -m window $firstManagedWindow --focus
    fi
    echo "Refocused to managed window $firstManagedWindow"
}

function sendToShelf() {
    yabai -m window $winId --space $SHELF_SPACE
    source /tmp/yab_prev_win
    if [[ ! -z $YAB_PREV_WIN && $YAB_PREV_WIN != $winId ]]; then
        yabai -m window $YAB_PREV_WIN --focus
        echo "Moved focus to previous window $YAB_PREV_WIN"
    fi
}


function pullFromShelf() {
    echo "YAB_PREV_WIN=${current[1]}" > /tmp/yab_prev_win
    echo "Moving window $winId to space ${current[0]}"
    yabai -m window $winId --space ${current[0]}
    # if the last command succeeded; then
    if [[ $? -eq 0 ]]; then
        echo "Moving focus to window $winId"
        yabai -m window $winId --focus &
    fi
    echo "Done"
}

windowIdentifier=$1
echo "winident" $windowIdentifier
if [[ -z $windowIdentifier ]]; then
    echo "No window identifier provided" >&2
    exit 1
fi

if [[ $windowIdentifier == 'display' ]]; then
    refocusManagedWindow
    exit 0
fi

if [[ -z ${configuredWindowFilters[$windowIdentifier]} ]]; then
    echo "No window filter configured for $windowIdentifier" >&2
    exit 1
fi

window=$(getTargetWindow $windowIdentifier)
echo "target" $window
if [[ -z $window ]]; then
    echo "No window found for identifier $windowIdentifier" >&2
    exit 1
fi

echo "get current space"
current=( $(getCurrentSpace) )
if [[ -z $current ]]; then
    echo "No current space found" >&2
    exit 1
fi
windowArr=( $(echo $window | gojq '. | (.id, .space, ."has-focus")') )

echo "prewinvar"
winId="${windowArr[0]}"
winSpace="${windowArr[1]}"
winFocus="${windowArr[2]}"
echo "prepull"
if [[ $winSpace == "${current[0]}" && $winFocus == 'true' ]]; then
    sendToShelf
else
    pullFromShelf
fi
